services:
  postgres:
    image: postgres:16.2
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - keycloak_network
    restart: unless-stopped
    ports:
      - 5438:5432

  keycloak:
    # image: lasthour/keycloak:1.0.2
    image: quay.io/keycloak/keycloak:26.1.0
    command: start
    volumes:
      - ./providers:/opt/keycloak/providers
    environment:

      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KC_HOSTNAME_ADMIN_URL: http://localhost:8081

      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - 8081:8080
      - 8082:8080

    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - keycloak_network

volumes:
  postgres_keycloak_data:
    driver: local

networks:
  keycloak_network: {}
